language: bash

services:
  - docker

script:
  - docker build -t psol ./
  - docker run --rm -v $PWD:/tmp psol sh -c "cp /usr/src/modpagespeed/psol.tar.gz /tmp/"

deploy:
  - provider: releases
    api_key: $GITHUB_ACCESS_TOKEN
    overwrite: true
    skip_cleanup: true
    file_glob: true
    file:
      - psol.tar.gz
    on:
      tags: true
